name: userscript-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/userscript/src/*.user.ts'
      - 'packages/userscript/.eslintrc.json'
  push:
    branches:
      - main
    paths:
      - 'packages/userscript/src/*.user.ts'
      - 'packages/userscript/.eslintrc.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm lint -w '@w0s/userscript'
